### ISSUE TITLE
ERROR in DpDatePickerModule is not an NgModule

### ISSUE THREAD

**Issue by lautaros86** [vlio20/ng2-date-picker#47] opened 2017-04-06 12:41 UTC
**I had this error:**

***ERROR in DpDatePickerModule is not an NgModule***

**ng -v**

- @angular/cli: 1.0.0
- node: 6.9.5
- os: win32 x64
- @angular/common: 4.0.1
- @angular/compiler: 4.0.1
- @angular/core: 4.0.1
- @angular/forms: 4.0.1
- @angular/http: 4.0.1
- @angular/platform-browser: 4.0.1
- @angular/platform-browser-dynamic: 4.0.1
- @angular/router: 4.0.1
- @angular/cli: 1.0.0
- @angular/compiler-cli: 4.0.1

## i try use this module on a new proyect but error still happen. ##

- ng new testing
- cd testing
- npm install ng2-date-picker --save

> app.module.ts

`import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { AppComponent } from './app.component';
import {DpDatePickerModule} from 'ng2-date-picker';
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    DpDatePickerModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }`

> app.component.ts

`import { Component, ViewChild } from '@angular/core';
import { DpDayPickerComponent } from 'ng2-date-picker';
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  @ViewChild('dayPicker') dayPicker: DpDayPickerComponent;
  selectedDate;
  datePickerConfig = {
    "format": "DD/MM/YYYY",
  };
  public constructor() { }
  ngOnInit() {
  }
  show(date) {
    if (this.selectedDate) {
      console.log(this.selectedDate.format('DD/MM/YYYY'));
    }
  }
}`

> app.component.html

` 
		  <dp-day-picker 
          #dayPicker
          placeholder="DD/MM/YYYY"
          [(ngModel)]="selectedDate" 
          [config]="datePickerConfig"
          maxlength="10"
          ></dp-day-picker>
 `

**Comment by vlio20** [comment] 2017-04-06 12:42
This is a duplicate of #8.
You can use the master version or wait for the next release.

**Closed by vlio20** 2017-04-06 12:42 UTC
